version : '3'
services:
  app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro


    


