version : '3'
services:
  app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    command: tail -f /dev/null # avoid removing the container
    volumes:
    - ./:/var/www
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
